{ 
  "text" : "An issue was discovered in Cloud Foundry Foundation cf-release versions prior to v263; UAA release 2.x versions prior to v2.7.4.18, 3.6.x versions prior to v3.6.12, 3.9.x versions prior to v3.9.14, and other versions prior to v4.3.0; and UAA bosh release (uaa-release) 13.x versions prior to v13.16, 24.x versions prior to v24.11, 30.x versions prior to 30.4, and other versions prior to v40. There was an issue with forwarded http headers in UAA that could result in account corruption.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Identity#5a67b7b374427c8917866406d4222b95" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "cloud foundry foundation" ,
    "begin" : 27 ,
    "end" : 51 ,
    "canonicalForm" : "Cloud Foundry Foundation" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Protocol#80791b3ae7002cb88c246876d9faa8f8" ,
    "type" : "Protocol" ,
    "subType" : "Protocol" ,
    "value" : "http" ,
    "begin" : 427 ,
    "end" : 431 ,
    "canonicalForm" : "http" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [  ]
}
