{ 
  "text" : "An XSS vulnerability exists in framework/views/errorHandler/exception.php in Yii Framework 2.0.12 affecting the exception screen when debug mode is enabled, because $exception->errorInfo is mishandled.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Vulnerability#1abbde94976702e6def6c052a8ddc456" ,
    "type" : "Vulnerability" ,
    "subType" : "Vulnerability" ,
    "value" : "xss vulnerability" ,
    "begin" : 3 ,
    "end" : 20 ,
    "canonicalForm" : "XSS vulnerability" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "FileName#d56ae50ebb7348d2f47b5c59a3e6fd0c" ,
    "type" : "FileName" ,
    "subType" : "FileName" ,
    "value" : "/views/errorHandler/exception.php" ,
    "begin" : 40 ,
    "end" : 73 ,
    "canonicalForm" : "/views/errorHandler/exception.php" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "exist_in" ,
    "predicate" : { 
      "begin" : 21 ,
      "end" : 30 ,
      "surfaceForm" : "exists in"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 3 ,
      "end" : 20 ,
      "eid" : "E1" ,
      "canonicalForm" : "XSS vulnerability"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 40 ,
      "end" : 73 ,
      "eid" : "E2" ,
      "canonicalForm" : "/views/errorHandler/exception.php"
    }
    ,  ]
  }
  ,  ]
}
