{ 
  "text" : "The (1) backup (api/contrib/backups.py) and (2) volume transfer (contrib/volume_transfer.py) APIs in OpenStack Cinder Grizzly 2013.1.3 and earlier allows remote attackers to cause a denial of service (resource consumption and crash) via an XML Entity Expansion (XEE) attack.  NOTE: this issue is due to an incomplete fix for CVE-2013-1664.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "FilePath#cea70476bec18cb594f54ecc72654651" ,
    "type" : "FilePath" ,
    "subType" : "FilePath" ,
    "value" : "/contrib/backups" ,
    "begin" : 19 ,
    "end" : 35 ,
    "canonicalForm" : "/contrib/backups" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "DomainName#55653b8fa2d37af26e5b4f86df89be7d" ,
    "type" : "DomainName" ,
    "subType" : "DomainName" ,
    "value" : "backups.py" ,
    "begin" : 28 ,
    "end" : 38 ,
    "canonicalForm" : "backups.py" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "DomainName#1a5fc0e8aeb51bc5a0e22bb20e40181f" ,
    "type" : "DomainName" ,
    "subType" : "DomainName" ,
    "value" : "volume_transfer.py" ,
    "begin" : 73 ,
    "end" : 91 ,
    "canonicalForm" : "volume_transfer.py" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 182 ,
    "end" : 199 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E5" ,
    "keyid" : "Vulnerability#fab67dd75ff4aab13c5e9b34aa953651" ,
    "type" : "Vulnerability" ,
    "subType" : "CVE" ,
    "value" : "cve-2013-1664" ,
    "begin" : 325 ,
    "end" : 338 ,
    "canonicalForm" : "CVE-2013-1664" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [  ]
}
