{ 
  "text" : "The tty_open function in drivers/tty/tty_io.c in the Linux kernel before 3.1.1 mishandles a driver-lookup failure, which allows local users to cause a denial of service (NULL pointer dereference and system crash) or possibly have unspecified other impact via crafted access to a device file under the /dev/pts directory.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "FilePath#13b75b83cf2cf8aa1b6bd23fdfec8998" ,
    "type" : "FilePath" ,
    "subType" : "FilePath" ,
    "value" : "/tty/tty_io" ,
    "begin" : 32 ,
    "end" : 43 ,
    "canonicalForm" : "/tty/tty_io" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Identity#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "linux" ,
    "begin" : 53 ,
    "end" : 58 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Product#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Product" ,
    "subType" : "OperatingSystem" ,
    "value" : "linux" ,
    "begin" : 53 ,
    "end" : 58 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "48967fd9a1b1949a175ddec2c2bc2d6e" ,
    "type" : "MiscEntity" ,
    "subType" : "user" ,
    "value" : "local user" ,
    "begin" : 128 ,
    "end" : 139 ,
    "canonicalForm" : "local user" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E5" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 151 ,
    "end" : 168 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 32 ,
      "end" : 43 ,
      "eid" : "E1" ,
      "canonicalForm" : "/tty/tty_io"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 53 ,
      "end" : 58 ,
      "eid" : "E3" ,
      "canonicalForm" : "Linux"
    }
    ,  ]
  }
  , { 
    "rid" : "R2" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 53 ,
      "end" : 58 ,
      "eid" : "E3" ,
      "canonicalForm" : "Linux"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 151 ,
      "end" : 168 ,
      "eid" : "E5" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R3" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 32 ,
      "end" : 43 ,
      "eid" : "E1" ,
      "canonicalForm" : "/tty/tty_io"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 151 ,
      "end" : 168 ,
      "eid" : "E5" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R4" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 53 ,
      "end" : 58 ,
      "eid" : "E2" ,
      "canonicalForm" : "Linux"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 151 ,
      "end" : 168 ,
      "eid" : "E5" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R5" ,
    "type" : "cause" ,
    "predicate" : { 
      "begin" : 140 ,
      "end" : 224 ,
      "surfaceForm" : "to cause a denial of service (NULL pointer dereference and system crash) or possibly"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 128 ,
      "end" : 139 ,
      "eid" : "E4" ,
      "canonicalForm" : "local user"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 151 ,
      "end" : 168 ,
      "eid" : "E5" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  ,  ]
}
