{ 
  "text" : "An issue was discovered in libgig 4.1.0. There is an out of bounds read in gig::File::UpdateChunks in gig.cpp.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "FileName#521e269a300cf0e9dde8139832e8b92d" ,
    "type" : "FileName" ,
    "subType" : "FileName" ,
    "value" : "gig.cpp" ,
    "begin" : 102 ,
    "end" : 109 ,
    "canonicalForm" : "gig.cpp" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [  ]
}
