{ 
  "text" : "An issue was discovered in the Ldap component in Symfony 2.8.x before 2.8.37, 3.3.x before 3.3.17, 3.4.x before 3.4.7, and 4.0.x before 4.0.7. It allows remote attackers to bypass authentication by logging in with a \"null\" password and valid username, which triggers an unauthenticated bind.  NOTE: this issue exists because of an incomplete fix for CVE-2016-2403.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "ThreatActor#d0f531219210b35f7261f3d6049ee44c" ,
    "type" : "ThreatActor" ,
    "subType" : "ThreatActor" ,
    "value" : "remote attacker" ,
    "begin" : 153 ,
    "end" : 169 ,
    "canonicalForm" : "remote attacker" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "6fa691d2c07bea6ae78b7022c80e9d20" ,
    "type" : "MiscEntity" ,
    "subType" : "authentication" ,
    "value" : "authentication" ,
    "begin" : 180 ,
    "end" : 194 ,
    "canonicalForm" : "authentication" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Vulnerability#fbee77384f5c1bc6bfbaf63b8790b538" ,
    "type" : "Vulnerability" ,
    "subType" : "CVE" ,
    "value" : "cve-2016-2403" ,
    "begin" : 350 ,
    "end" : 363 ,
    "canonicalForm" : "CVE-2016-2403" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "bypass" ,
    "predicate" : { 
      "begin" : 170 ,
      "end" : 179 ,
      "surfaceForm" : "to bypass"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 153 ,
      "end" : 169 ,
      "eid" : "E1" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 180 ,
      "end" : 194 ,
      "eid" : "E2" ,
      "canonicalForm" : "authentication"
    }
    ,  ]
  }
  ,  ]
}
