{ 
  "text" : "Use After Free vulnerability in the Zephyr shell allows a serial or telnet connected user to cause denial of service, and possibly remote code execution. This issue affects: Zephyr shell versions prior to 1.14.0 on all.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Vulnerability#4e9c8c30433d67f110437a7b46c5f4a1" ,
    "type" : "Vulnerability" ,
    "subType" : "Vulnerability" ,
    "value" : "free vulnerability" ,
    "begin" : 10 ,
    "end" : 28 ,
    "canonicalForm" : "Free vulnerability" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Protocol#03583cd75bf401944b018f81b3f6916d" ,
    "type" : "Protocol" ,
    "subType" : "Protocol" ,
    "value" : "telnet" ,
    "begin" : 68 ,
    "end" : 74 ,
    "canonicalForm" : "telnet" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 99 ,
    "end" : 116 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "TTP#cc08fcc152a544c7bf56489571f8cb60" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "remote code execution" ,
    "begin" : 131 ,
    "end" : 152 ,
    "canonicalForm" : "remote code execution" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [  ]
}
