{ 
  "text" : "backintime (aka Back in Time) before 1.1.24 did improper escaping/quoting of file paths used as arguments to the 'notify-send' command, leading to some parts of file paths being executed as shell commands within an os.system call in qt4/plugins/notifyplugin.py. This could allow an attacker to craft an unreadable file with a specific name to run arbitrary shell commands.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "FilePath#0f683242ab9853e7da1920455e3ebddc" ,
    "type" : "FilePath" ,
    "subType" : "FilePath" ,
    "value" : "/plugins/notifyplugin" ,
    "begin" : 236 ,
    "end" : 257 ,
    "canonicalForm" : "/plugins/notifyplugin" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "DomainName#9a659676feeff8dc09550d0287454f63" ,
    "type" : "DomainName" ,
    "subType" : "DomainName" ,
    "value" : "notifyplugin.py" ,
    "begin" : 245 ,
    "end" : 260 ,
    "canonicalForm" : "notifyplugin.py" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 236 ,
      "end" : 257 ,
      "eid" : "E1" ,
      "canonicalForm" : "/plugins/notifyplugin"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 245 ,
      "end" : 260 ,
      "eid" : "E2" ,
      "canonicalForm" : "notifyplugin.py"
    }
    ,  ]
  }
  ,  ]
}
