{ 
  "text" : "Race condition in ZEO/StorageServer.py in Zope Object Database (ZODB) before 3.10.0 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "AvSignature#dd43f15121fb7bf3adb1a35b21ae6529" ,
    "type" : "AvSignature" ,
    "subType" : "AvSignature" ,
    "value" : "zeo/storageserver.py" ,
    "begin" : 18 ,
    "end" : 38 ,
    "canonicalForm" : "ZEO/StorageServer.py" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "ThreatActor#d0f531219210b35f7261f3d6049ee44c" ,
    "type" : "ThreatActor" ,
    "subType" : "ThreatActor" ,
    "value" : "remote attacker" ,
    "begin" : 91 ,
    "end" : 107 ,
    "canonicalForm" : "remote attacker" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 119 ,
    "end" : 136 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "Vulnerability#9971dde2f1ae76e1a6e301bdf91249c0" ,
    "type" : "Vulnerability" ,
    "subType" : "CVE" ,
    "value" : "cve-2010-3492" ,
    "begin" : 404 ,
    "end" : 417 ,
    "canonicalForm" : "CVE-2010-3492" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "allow" ,
    "predicate" : { 
      "begin" : 84 ,
      "end" : 90 ,
      "surfaceForm" : "allows"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 18 ,
      "end" : 38 ,
      "eid" : "E1" ,
      "canonicalForm" : "ZEO/StorageServer.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 91 ,
      "end" : 107 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    ,  ]
  }
  , { 
    "rid" : "R2" ,
    "type" : "relatedVulnerability" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 18 ,
      "end" : 38 ,
      "eid" : "E1" ,
      "canonicalForm" : "ZEO/StorageServer.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 404 ,
      "end" : 417 ,
      "eid" : "E4" ,
      "canonicalForm" : "CVE-2010-3492"
    }
    ,  ]
  }
  , { 
    "rid" : "R3" ,
    "type" : "relatedTTP" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 18 ,
      "end" : 38 ,
      "eid" : "E1" ,
      "canonicalForm" : "ZEO/StorageServer.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 119 ,
      "end" : 136 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R4" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 18 ,
      "end" : 38 ,
      "eid" : "E1" ,
      "canonicalForm" : "ZEO/StorageServer.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 119 ,
      "end" : 136 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R5" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 119 ,
      "end" : 136 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 404 ,
      "end" : 417 ,
      "eid" : "E4" ,
      "canonicalForm" : "CVE-2010-3492"
    }
    ,  ]
  }
  , { 
    "rid" : "R6" ,
    "type" : "relatedThreatActor" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 18 ,
      "end" : 38 ,
      "eid" : "E1" ,
      "canonicalForm" : "ZEO/StorageServer.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 91 ,
      "end" : 107 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    ,  ]
  }
  , { 
    "rid" : "R7" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 18 ,
      "end" : 38 ,
      "eid" : "E1" ,
      "canonicalForm" : "ZEO/StorageServer.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 404 ,
      "end" : 417 ,
      "eid" : "E4" ,
      "canonicalForm" : "CVE-2010-3492"
    }
    ,  ]
  }
  , { 
    "rid" : "R8" ,
    "type" : "cause" ,
    "predicate" : { 
      "begin" : 108 ,
      "end" : 116 ,
      "surfaceForm" : "to cause"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 91 ,
      "end" : 107 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 119 ,
      "end" : 136 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R9" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 91 ,
      "end" : 107 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 404 ,
      "end" : 417 ,
      "eid" : "E4" ,
      "canonicalForm" : "CVE-2010-3492"
    }
    ,  ]
  }
  ,  ]
}
