{ 
  "text" : "proxy.c in libpurple in Pidgin before 2.10.4 does not properly handle canceled SOCKS5 connection attempts, which allows user-assisted remote authenticated users to cause a denial of service (application crash) via a sequence of XMPP file-transfer requests.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "618c2ca101bb7338abcf8f5789bbfdfb" ,
    "type" : "MiscEntity" ,
    "subType" : "user" ,
    "value" : "assisted remote authenticated user" ,
    "begin" : 125 ,
    "end" : 160 ,
    "canonicalForm" : "assisted remote authenticated user" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 172 ,
    "end" : 189 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "cause" ,
    "predicate" : { 
      "begin" : 161 ,
      "end" : 169 ,
      "surfaceForm" : "to cause"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 125 ,
      "end" : 160 ,
      "eid" : "E1" ,
      "canonicalForm" : "assisted remote authenticated user"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 172 ,
      "end" : 189 ,
      "eid" : "E2" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  ,  ]
}
