{ 
  "text" : "An issue was discovered in OpenStack Nova 15.x through 15.1.0 and 16.x through 16.1.1. By detaching and reattaching an encrypted volume, an attacker may access the underlying raw volume and corrupt the LUKS header, resulting in a denial of service attack on the compute host. (The same code error also results in data loss, but that is not a vulnerability because the user loses their own data.) All Nova setups supporting encrypted volumes are affected.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Campaign#10e60b758ba8d4e7d9d47c2697d42f7b" ,
    "type" : "Campaign" ,
    "subType" : "Campaign" ,
    "value" : "denial of service attack" ,
    "begin" : 230 ,
    "end" : 254 ,
    "canonicalForm" : "denial of service attack" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 230 ,
    "end" : 247 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [  ]
}
