{ 
  "text" : "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "Identity#d5493f7052b732566ed9f9a0aaec7d2a" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "python cryptographic authority" ,
    "begin" : 0 ,
    "end" : 30 ,
    "canonicalForm" : "Python Cryptographic Authority" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "e7bcc6e091b8d20ed1217032325e74dc" ,
    "type" : "MiscEntity" ,
    "subType" : "CWE" ,
    "value" : "CWE" ,
    "begin" : 74 ,
    "end" : 77 ,
    "canonicalForm" : "CWE" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Vulnerability#c0c513d429664f8f13f33adf02ae26a2" ,
    "type" : "Vulnerability" ,
    "subType" : "Vulnerability" ,
    "value" : "reference vulnerability" ,
    "begin" : 133 ,
    "end" : 156 ,
    "canonicalForm" : "Reference vulnerability" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 194 ,
    "end" : 211 ,
    "canonicalForm" : "Denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 0 ,
      "end" : 30 ,
      "eid" : "E1" ,
      "canonicalForm" : "Python Cryptographic Authority"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 133 ,
      "end" : 156 ,
      "eid" : "E3" ,
      "canonicalForm" : "Reference vulnerability"
    }
    ,  ]
  }
  , { 
    "rid" : "R2" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 0 ,
      "end" : 30 ,
      "eid" : "E1" ,
      "canonicalForm" : "Python Cryptographic Authority"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 194 ,
      "end" : 211 ,
      "eid" : "E4" ,
      "canonicalForm" : "Denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R3" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 133 ,
      "end" : 156 ,
      "eid" : "E3" ,
      "canonicalForm" : "Reference vulnerability"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 194 ,
      "end" : 211 ,
      "eid" : "E4" ,
      "canonicalForm" : "Denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R4" ,
    "type" : "contain" ,
    "predicate" : { 
      "begin" : 63 ,
      "end" : 71 ,
      "surfaceForm" : "contains"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 0 ,
      "end" : 30 ,
      "eid" : "E1" ,
      "canonicalForm" : "Python Cryptographic Authority"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 74 ,
      "end" : 77 ,
      "eid" : "E2" ,
      "canonicalForm" : "CWE"
    }
    ,  ]
  }
  ,  ]
}
