{ 
  "text" : "An issue was discovered in Libav 12.3. A read access violation in the mov_probe function in libavformat/mov.c allows remote attackers to cause a denial of service (application crash), as demonstrated by avconv.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "f2cf42f1a646198c72c28d3adf9afbda" ,
    "type" : "MiscEntity" ,
    "subType" : "function" ,
    "value" : "probe function" ,
    "begin" : 74 ,
    "end" : 109 ,
    "canonicalForm" : "probe function" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "ThreatActor#d0f531219210b35f7261f3d6049ee44c" ,
    "type" : "ThreatActor" ,
    "subType" : "ThreatActor" ,
    "value" : "remote attacker" ,
    "begin" : 117 ,
    "end" : 133 ,
    "canonicalForm" : "remote attacker" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 145 ,
    "end" : 162 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "cause" ,
    "predicate" : { 
      "begin" : 134 ,
      "end" : 142 ,
      "surfaceForm" : "to cause"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 117 ,
      "end" : 133 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 145 ,
      "end" : 162 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R2" ,
    "type" : "allow" ,
    "predicate" : { 
      "begin" : 110 ,
      "end" : 116 ,
      "surfaceForm" : "allows"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 74 ,
      "end" : 109 ,
      "eid" : "E1" ,
      "canonicalForm" : "probe function"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 117 ,
      "end" : 133 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    ,  ]
  }
  ,  ]
}
