{ 
  "text" : "A vulnerability was discovered in DNS resolver component of knot resolver through version 3.2.0 before 4.1.0 which allows remote attackers to bypass DNSSEC validation for non-existence answer. NXDOMAIN answer would get passed through to the client even if its DNSSEC validation failed, instead of sending a SERVFAIL packet. Caching is not affected by this particular bug but see CVE-2019-10191.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "ThreatActor#d0f531219210b35f7261f3d6049ee44c" ,
    "type" : "ThreatActor" ,
    "subType" : "ThreatActor" ,
    "value" : "remote attacker" ,
    "begin" : 122 ,
    "end" : 138 ,
    "canonicalForm" : "remote attacker" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "1e9d8756f7e33f5d76565b0529eaf232" ,
    "type" : "MiscEntity" ,
    "subType" : "validation" ,
    "value" : "DNSSEC validation" ,
    "begin" : 149 ,
    "end" : 166 ,
    "canonicalForm" : "DNSSEC validation" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "bypass" ,
    "predicate" : { 
      "begin" : 139 ,
      "end" : 148 ,
      "surfaceForm" : "to bypass"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 122 ,
      "end" : 138 ,
      "eid" : "E1" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 149 ,
      "end" : 166 ,
      "eid" : "E2" ,
      "canonicalForm" : "DNSSEC validation"
    }
    ,  ]
  }
  ,  ]
}
